### ISSUE TITLE
/usr/bin/env: ‘node’: No such file or directory

### ISSUE THREAD

**Issue by mdivk** [SunGard-Labs/fix2json#17]
After the following two steps to install fix2json as per the description
sudo apt install npm
sudo npm install -g fix2json

I ran the same command: 
fix2json -p dict/FIX50SP2.CME.xml XCME_MD_GE_FUT_20160315.gz
and I received error of: /usr/bin/env: ‘node’: No such file or directory

It would be appreciated if you can point out what is missing here?

Thank you.

**Comment by salsferrazza** [comment]
Hi, is node installed on the host?

`sudo apt-get install nodejs`

**Comment by mdivk** [comment]
I did install node already and runnig fix2json still showing
/usr/bin/env: ‘node’: No such file or directory

where should I run the fix2json? should I start node before I run the
fix2json?

I am very new to Solr and Node.JS

Thank you.



*------------------------------------------------*
*Sincerely yours,*


*Raymond*

**Comment by salsferrazza** [comment]
it's been a while, but did you ever resolve the issue?

**Comment by salsferrazza** [comment]
Closed for inactivity - please re-open if still having issues.
